project:
  type: book

book:
  title: "WiP: Physical Sensing Coupled with Physics Based Machine Learning"  # Sensing, Simulation, and ... 
  author: "John Waczak"
  date: today
  chapters:
    - index.qmd
    - PhysicalContext/Overview.qmd
    - PhysicalSensing/Overview.qmd
    - ComputationalTools/Overview.qmd
    - TheoreticalTools/Overview.qmd
    - ML/Overview.qmd
    - RobotTeam/Overview.qmd
    - ChemicalMechanism/Overview.qmd
    - TimeSeries/Overview.qmd
    - Discussion/Overview.qmd
    - Conclusions.qmd
    - Extras/TechnicalNotes.qmd
    - Extras/OtherTopics.qmd

    - references.qmd
  appendices:
    - Appendices/appendix.qmd
    - Appendices/EEG-band-discovery.qmd

  downloads: [pdf]

bibliography:
  - references.bib
  - Introduction/references.bib
  - PhysicalContext/references.bib
  - ML/references.bib

spacing: "doublespacing"
degreetype: "Dissertation"
degreefull: "Doctor of Philosophy"
degreeabbr: "PhD"
subject: "Physics"
graduationmonth: "May"
graduationyear: "2024"
previousdegrees: "BS, PhD"

committeechair: "David J. Lary"
committee1: "Christopher Simmons"
committee2: "David Lumley"
committee3: "Lindsay King"
committee4: "Joseph Izen"

copyright_year: 2024

dedication: |
  Update required!

acknowledgements: |
  Update required! Make sure to include lab colleagues *and* ActivePure colleagues and a nod to Dr. Cooper, OSU teachers, and friends...

abstract: |
  Update required!

biosketch: |
  Update required!

execute:
  freeze: auto
  echo: false

format:
  html:
    theme: cosmo
  utd-pdf:
#    pdf-engine: pdflatex
    keep-tex: true


