project:
  type: book
  output-dir: docs

book:
  title: "WiP: Physical Sensing Coupled with Physics Based Machine Learning"
  author: "John Waczak"
  date: today
  chapters:
    - index.qmd
    # - Introduction.qmd
    - GlobalChange.qmd
    - KeyTechnologies.qmd
    - ML.qmd
    - RobotTeam.qmd
    - SensorNetwork.qmd
    - MasterChemicalMechanism.qmd
    - references.qmd
  appendices:
    - appendix.qmd 

bibliography: references.bib

spacing: "doublespacing"
degreetype: "Dissertation"
degreefull: "Doctor of Philosophy"
degreeabbr: "PhD"
subject: "Physics"
graduationmonth: "May"
graduationyear: "2024"
previousdegrees: "BS, PhD"

committeechair: "David J. Lary"
committee1: "Christopher Simmons"
committee2: "Lindsay King"
committee3: "David Lumley"

copyright_year: 2024

dedication: |
  Update required!

acknowledgements: |
  Update required!

abstract: |
  Update required!

biosketch: |
  Update required!

execute:
  freeze: auto
  echo: false

format:
  html:
    theme: cosmo
  utd-pdf:
    keep-tex: true



