# Introduction


*NOTE*: For the proposal in particular, we should add a new section with timelines and a table of currently completed tasks.


*NOTE*: We want to emphasize the need for reproducible research paradigms. This motivates 


*NOTE*: for the area of uncertainty quantification via statistical machine learning methods we should emphasize the fact that uncertainty is challenging to quantify in physical systems but in the age of big data, we need not really on the assumption of conveniently shaped normal distributions-- we can do better. Instead, we let the data be our guide, deriving improved uncertainty bounds (in the statistical sense) with methods to track key diagnostic characteristics such as the relevant time scale. Further, in the domain of low-cost sensing, a key challenge is accurately quantifying uncertainty bounds for measurements as manufacturer provided estimates are almost always overly conservative (to minimize responsibility for variance, perhaps?)

*NOTE*: We should also mention (in our goals for the dissertation) that reproducibility is of critical importance (in physics, in machine learning, in scientific code, in analysis, etc...) with relevant statistics quoted (perhaps that nice interview from )


*NOTE*: explain Dr. Lary's principle of "Do the obvious thing: ask the obvious question, run the obvious experiment, perform the obvious analysis" as a guiding principle for the logical organization of this dissertation.



The goal of this thesis is advancing physical sensing in service of society to provide actionable insights. This goal is pursued by applying physics informed approaches together with a suite of sensing and computational technologies, implementing the reusable paradigm of software defined sensors, i.e. physical sensing elements wrapped in a software layer. This software layer can serve a variety of purposes such as calibration and the provision of enhanced or derived data products. It is part of a broader effort in the MINTS-AI laboratory at the University of Texas at Dallas. Where MINTS-AI is an acronym, **M**ulti-Scale **M**ulti-Use **Int**egrated **Int**elligent **Int**eractive **S**ensing in **S**ervice of **S**ociety for **A**ctionable **I**nsights.

Comprehensive environmental sensing is a timely and beneficial endeavor for a variety of reasons. The growing awareness of major environmental issues such as climate change, pollution, and habitat loss necessitates effective environmental monitoring and management. Comprehensive environmental sensing can provide real-time data on air and water quality, weather patterns, and other environmental factors, assisting in the identification and resolution of environmental issues. This assists in the development and implementation of policies and strategies aimed at reducing environmental impact and increasing sustainability. Given that, for instance, air quality can have significant effects on human health, this has particular societal value. 

Exposure to air pollution has been linked to a wide range of health effects [@Brook2008; @Kelly2011; @Xu2017], including respiratory and cardiovascular diseases, cancer, and adverse birth outcomes. Further, physical sensing provides valuable data and the basis for international assessments such as the Intergovernmental Panel on Climate Change (IPCC), which seeks to assess the science related to climate change and its impacts on natural and human systems [@IPCC1990; @IPCC1995; @IPCC2001; @IPCC2007a; @IPCC2007b; @IPCC2007c; @IPCC2013a; @IPCC2013b; @IPCC2014; @IPCC2018; @Friedlingstein2020; @Huang2017]. 

Comprehensive sensing of the environment can improve decision-making. The real-time and accurate data provided by environmental sensors can aid in informed decision-making regarding various aspects such as traffic management, industrial regulation, and crop planning. For instance, data on air quality can be used to inform decisions about reducing pollution levels, while data on weather patterns can help farmers to plan their crops and reduce water usage. Comprehensive sensing of the environment can be instrumental in emergency response. Real-time data on weather patterns, air quality, water levels and resources, and seismic activity can help emergency responders to prepare for and respond to natural disasters such as hurricanes, floods, and earthquakes. The quick and accurate information can enable effective and timely response, potentially saving lives and reducing the impact of the disaster. 

Many advances in technology have enabled the creation of comprehensive sensing systems that can monitor and analyze data from various sensors and devices in real-time. In this thesis we use a range of technologies including autonomous robotic teams [@Dunbabin2012; @Rubenstein2014; @Chen2017], hyperspectral imaging [@Plaza2009; @Li2018; @Zhu2017], mesh networks utilizing the Internet of Things (IoT) [@Gubbi2013; @Atzori2010; @Al-Fuqaha2015], machine learning (ML) [@Goodfellow2016; @LeCun2015; @Jordan2015], edge computing, high-performance computing,  wearable sensors and modern high-performance dynamic programming languages such as Julia [@Bezanson2017] designed for numerical and scientific computing. These technologies have facilitated the collection and processing of large amounts of data from multiple sources, resulting in more accurate and comprehensive environmental monitoring.



{{< include Introduction/DissertationGoal.qmd >}}

{{< include Introduction/GlobalChange.qmd >}}

{{< include Introduction/KeyTechnologies.qmd >}}

{{< include Introduction/ML.qmd >}}




NOTE:  perhaps add section on increasing concerns about indoor air quality (use EPA RFI document). I think ideally we should break down the introduction by sensing domain


<!-- Other sections to ponder:  -->

<!-- ## Particulate Matter  -->

<!-- - definitions  -->
<!-- - sensing methods  -->
<!-- - physics of...  -->
<!-- - air quality -->
<!-- - consequences of... -->

<!-- ## Optics of Aqueous Chemicals -->

<!-- - incident solar radiation  -->
<!-- - transport through the atmosphere -->
<!-- - Motivating relationship: Beer-Lambert Law -->
<!--   - what happens when we have multiple dissolved species? i.e. justification for use of ML -->
<!--   -  -->
<!-- - section in jackson about reflectivity of water -->
<!-- - Types of spectra we deal with:  -->
<!--   - reflectance  -->
<!--   - radiance  -->
<!--   - solar irradiance -->
<!-- - Solar Geometry  -->

<!-- ## Chemical Reaction Kinetics for the Working Physicist -->

<!-- - reaction extent  -->
<!-- - Gibbs free energy (mountain-valley-hill) -->
<!-- - reaction order  -->
<!-- - reaction networks  -->
<!-- - graph theory for reaction networks  -->
<!-- - fundamental reactions  -->
<!-- - bimolecular, trimolecular  -->
<!-- - derivation via kinetic theory  -->
<!-- - the Maxwell-Boltzmann distribution  -->
<!-- - Photolysis -->

<!-- ## Remote Sensing  -->

<!-- - Hyper spectral images  -->
<!-- - types of Imagers  -->
<!-- - Vegetation Indices  -->
<!-- - Orthorectification + Georeferencing = Georectification -->


<!-- ## On the calibration of measurement devices...  -->

<!-- - discuss standard curve fitting used for *most* reference instrument calibration -->
<!-- - discuss value of ML for doing the same  -->
<!-- - stress importance of probabilistic models  -->
<!-- - non-parametric, non-linear... -->


<!-- ## Uncertainty Quantification -->

<!-- - standard methods (linear propagation of uncertainty) -->
<!-- - `Measurments.jl`, i.e., why Julia is awesome -->
<!-- - Bayesian frameworks, Ensemble sampling, Markov-Chain-Monte-Carlo -->
<!-- - Bayesian Regression -->
<!-- - Kernelization and Gaussian Processes -->
<!-- - Conformal Prediction and Frequentist Statistics -->
