# Super Resolution

## Cloud & Shadow Mask for Sentinel-2
### ML Type 
- Supervised Classification 
### ML Methods 
- Single Pixel w/ Tree Based Methods 
- Deep NN with Convolutional Layers
### Features 
- Sentinel 2 Multi-band Imagery 
- Land Type 
- Viewing Geometry 
- Solar Geometry
### Targets
- Sentinel 2 Cloud Mask + Cloud Shadow Mask

## Cloud & Shadow Fill 
### ML Type 
- supervised regression
### ML Methods 
- pixel based (Would it make sense to do something else here?)
### Features 
- Sentinel 2 Multi-band Imagery 
- Sentinel 2 Cloud Mask & Cloud Shadow Mask 
- Sentinel 1 SAR Variables (GRD or SLC or both?)
- 10 m Digital Elevation Map
- Viewing Geometry 
- Solar Geometry
- Land Type
### Targets
- *Cloudless & Shadowless* Sentinel 2 Multi-band imagery 

## Sentinel 2 RGB *Spatial* Super Resolution 
### ML Type 
- Supervised Regression
### ML Methods 
- This has to be a Deep NN method using convolution to get the upsampling. I don't think we can do this with pixel based models (using tree methods)
- Probably should use a GAN
### Features
- High (spatial) Resolution NAIP RGB Image
- Sentinel 2 Multi-band Imagery 
- Sentinel 1 SAR Variables (GRD or SLC or both?)
- 10 m Digital Elevation Map
- Viewing Geometry 
- Solar Geometry
- Land Type
### Targets
- Sentinel RGB Bands @ NAIP Resolution
### Loss Function Terms
### Notes 
We could make a model that uses all 3 bands (RGB) simultaneously, or we can make a model for a single band that we validate against R, G, and B bands individually. This has the added perc of increasing the training samples. This will be much easier to then apply to *all* bands of the sentinel imagery (and perhaps Sentinel 1, etc...)  independently. We could try: 
- Red, Green, Blue bands separately 
- Black and White converted RGB image
- Data Augmentation via Scaling / Rotation / Reflection

## Sentinel 2 Multiband *Spatial* Super Resolution 
### ML Type 
- Supervised Regression
### ML Methods 
- This has to be a Deep NN method using convolution to get the upsampling. I don't think we can do this with pixel based models (using tree methods)
- Probably should use a GAN
### Features
- High (spatial) Resolution NAIP RGB Image
- Sentinel 2 Multi-band Imagery 
- Sentinel 1 SAR Variables (GRD or SLC or both?)
- 10 m Digital Elevation Map
- Viewing Geometry 
- Solar Geometry
- Land Type
### Targets
- Sentinel RGB Bands @ NAIP Resolution
### Loss Function Terms


## Sentinel 2 Multiband *Spectral* Super Resolution
### ML Type 
- Supervised Regression
### ML Methods 
- This can be pixel based
### Features
- Sentinel 2 Multi-band Imagery 
- Sentinel 1 SAR Variables (GRD or SLC or both?)
- 10 m Digital Elevation Map
- Viewing Geometry 
- Solar Geometry
- UAV Hyperspectral Image
### Targets
- Sentinel *Hyperspectral*  Imagery (i.e. Sentinel at all HSI Bands)
### Loss Function Terms

