## Indoor Air Quality


### Better Indoor Air Quality Management To Help Reduce COVID-19 and Other Disease Transmission in Buildings:  Technical Assistance Needs and Priorities to Improve Public Health


“Ventilation, filtration, and air cleaning in buildings are essential components of a multilayered approach to preventing disease transmission, including COVID-19.”


This statement serves as the foundation for The Clean Air in Buildings Challenge and this RFI. We completely agree with this premise, but we believe the ‘order of operations’ - among ventilation, filtration, and air cleaning - should be the primary focus of inquiry, and effective and safe air cleaning innovations should be a focus deserving full consideration. We can reconcile multiple, often competing goals by informing and empowering schools and commercial buildings to adopt a  Clean First' mentality [@enVerid; @enVeridWhitePaper], which we will explore in this response, as well as examine the ‘art of the possible’ by taking a critical look at the 21$^{st}$ century innovations we believe will be essential to the practical pursuit and achievement of The Clean Air in Buildings Challenge goals/objectives. We will demonstrate the necessary considerations of a Clean First' [@enVerid; @enVeridWhitePaper] approach as well as highlight its additional benefits in this response, which include but are not limited to:

- Reduced mechanical system energy consumption.
- Reductions in healthcare-acquired infections (HAIs) that are statistically significant in healthcare settings.
- Real-world testing/proof of lower microbiological burden (total and culturable bacteria, fungi, and their spores) in addition to improved ventilation/filtration alone.
- Reduced school absenteeism.
- Increased resiliency to future pandemics and communicable diseases.
- Reduction in airborne communicable disease and allergen loads. 

The real challenges posed by global environmental change, combined with rising utility costs as a result of inflation and geopolitical shocks to energy supply chains, have created an implicit dichotomy between climate and public health goals. As Prof. Bahnfleth has said,

