## Remote Sensing 

mention different types of satellite data platforms (mostly optical), differences in orbits, coverage, etc... Also good to discuss the increasing use of drones for a variety of applications including intelligent agriculture, geophysics, mapping, etc...



- **Remote Sensing**: data acquisition, processing, and interpretation of images, and related data, obtained from aircraft and satellites that record the interaction between matter and electromagnetic radiation
- **Source**: the source of electromagnetic radiation, e.g. the sun, black-body radiation, microwave radar, etc...
- **Atmospheric Radiation**: The EM radiation propagating through the atmosphere. Moderated by various processes including absorption and scattering
- **Earth's Surface Interation**: Amount and spectral distribution of radiation emitted/reflected by the earth's surface. This depends on 
  - physical properties of the matter 
  - wavelength of EM radiation that is sensed

### Infrared Sensing Phenomenology 

- Main passive sources of EM radiation for remote sensing are light emitted by the sun and the self-emission via black-body radiation of objects due to their temperature. 

#### Sources of Infrared Radiation 

- **spectral radiant exitance** power per unit area emitted by the sun. We can treat this as a black body with temperature $5800 K$, maximum emittance at $\lambda = 0.50$ $\mu m$. 
- The Earth is ~$300 K$ with maximum spectral radiant emittance at $\lambda = 9.7$ $\mu m$. This is known as the **thermal infrared**

#### Atmospheric Propagation 

- Key parameter is the **path length** of atmosphered traveled through before it arrives at the remote sensing system. Main effects are:
  - **Atmospheric Scattering**: diffusion of radiation by particles in the atmosphere
  - **Absorption**
- Useful remote sensing spectral regions are obtained via the **Transmission Spectrum**.
  - **Reflective Range**: $0.35-2.5$ $\mu m$. Dominated by solar illumination
  - **Water Absorption**: $0.2-2.5$ $\mu m$. 
- **Atmospheric Windows**: Regions of low atmospheric absorption 


#### Reflectance and Emissivity Spectra

There are three processes that occur when EM radiation meets and interface: 

1. **Reflection**: Solar illumination dominates here. Consequently, this part of the spectrum is used to characterize the surface
   - *Specular Reflectors*: Flat surfaces that act like mirrors, i.e. $\theta_i = \theta_r$. 
   - *Diffuse (Lambertian) Reflectors*: Rough surfaces that reflect uniformly in all directions. 
   - *Real Reflectors*: Somewhere between the specular and diffuse.
2. **Absorption** 
3. **Transmission**

- Fractions vary as a function of $\lambda$ 
- Remote sensing usually cares about *diffuse* reflectors because this is the dominant type of most materials (water being an exception). 
- Reflectance of a material is characterized by its **Reflectance Spectrum**, that is, the percent of incident light reflected as a function of wavelength. 
  - Dips in reflectance spectrum are called **absorption features**
  - Peaks are called **Reflectance Peaks**
- **Emissivity Spectrum**: The ratio of radiant emittance at a given temperature to the radiant emittance of a black body at the same temperature. 

