## Uncertainty Estimation Via Time Series Sampling 

### Types Of Uncertainty 
### Instrument Uncertainty
### Representativeness Uncertainty
### Variograms
### Mutual Information
### Auto-correlation

## Time Series Chaos
### What is Chaos? 
### Lyapunov Exponents
### Fractal Dimension


## Koopman Operator Theory

## Time Series Modeling Methods
### Token-Hankel Delay Embeddings
### Embedding Theorems (are magic)
### Determination of Optimal Lag
### Determination of Intrinsic Dimension (kind of unnecessary given *large enough* embedding)
### DMD and HAVOK
### Hamiltonian Neural Networks


## Time Series Classification
### Considerations for Batching of Time Series for ML Models
### K-means Clustering 
### Self Organizing Maps
### Generative Topographic Maps
### Chaos Classification via HAVOK 
### Symplectic and Normal Gradients for HNN


## Motivating Example: Lorenz63 System
### Origin of Lorenz System
### Time Scale Analysis and Variography
### Embedding
### Modeling
### Classification


## Real Example 1: PM Data
### Origin of Lorenz System
### Time Scale Analysis and Variography
### Embedding
### Modeling
### Classification

## Real Example 2: Biometric Data
### Origin of Lorenz System
### Time Scale Analysis and Variography
### Embedding
### Modeling
### Classification


## Real Example 3: Stock Market Analysis
### Origin of Lorenz System
### Time Scale Analysis and Variography
### Embedding
### Modeling
### Classification
